name: flutter_music
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # 数据请求
  dio: ^3.0.8
  # Dart常用工具类库
  common_utils: ^1.1.3
  # 状态管理，UI、数据 分离
  provider: ^4.0.1
  # 本地存储数据，持久化
  shared_preferences: ^0.5.6
  # 屏幕适配
  flutter_screenutil: ^1.0.1
  # 路由管理
  fluro: ^1.5.1
  # dio cookie 工具
  dio_cookie_manager: ^1.0.0
  # Cookie 管理
  cookie_jar: ^1.0.1
  # 权限处理
  permission_handler: ^4.0.0
  # 沙盒路径
  path_provider: ^1.5.1
  # Image 扩展
  extended_image: ^0.6.8
  # 依赖注入
  get_it: ^3.1.0
  # 信息提示框  
  fluttertoast: ^3.1.3
  
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
